apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: proselyte-system
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: postgres
  keycloak-user: keycloak
  keycloak-password: keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: proselyte-system
type: Opaque
stringData:
  admin-username: admin
  admin-password: admin